import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import {useRouter} from "next/router";
import styles from "../../styles/Home.module.css";

export default function Main() {
  const router = useRouter()
  
  const logout = async () => {
    const {data} = await axios.get('/api')
    if (data.message !== "OK") alert('Logout Failed')
    else router.push('/')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Main Page
        </h1>
        <button onClick={logout}>Logout</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
